### PR TITLE
Logo alteration: replaced the letter A with L.

### PR DESCRIPTION
**Pull request by AustejaKazlauskyte**
I altered the logo, creating a letter L instead of A. I did it using the grid system. First, I drew many vertical and horizontal lines in the view box, they allowed me to be precise when creating the image. Then, I drew a path for L and I filled it with white color. 

I would gladly make modifications if needed.

### CODE REVIEW

**Comment by rootis** [comment]
It looks great. You could move letter "L" up for 1 or 2 pixels maybe..? It's up to you. And after that generate favicon.ico file using that logo. For favicon file we should choose darker background for all shield.

**Comment by rootis** [comment]
And one more small adjustment: enable the ability to click on the logo too. After this action user should be redirected to the home page (the same as clicking on project name).

**Comment by AustejaKazlauskyte** [comment]
Will do.

**Comment by rootis** [comment]
Version update is missing. In file: version.component.html -> increase version number +1

**Pull request merged**
